### ISSUE TITLE
licenses/embed.go:24:12: pattern */[^_]*: no matching files found

### ISSUE THREAD

**Issue by yurivict** [divVerent/aaaaxy#22] opened 2022-05-18 04:14 UTC
When built with ```-tags=embed``` the build breaks:
```
licenses/embed.go:24:12: pattern */[^_]*: no matching files found
*** Error code 1
```

OS: FreeBSD 13

**Comment by yurivict** [comment] 2022-05-18 04:29
Not sure why licenses even need to be embedded into the executable.
This adds complexity and potential for bugs without any visible benefit.

**Comment by divVerent** [comment] 2022-05-18 09:24
The benefit is that if someone just redistributes the bare binaries,
license info remains available "somehow". This helps not breaking the law
when e.g. compiling to AppImage.

As for that pattern I need to check - could it just be that FreeBSD does
not support this glob syntax? What I want to achieve is to exclude the
_editorimgs, _src and _generated folders.

**Comment by yurivict** [comment] 2022-05-18 15:26
Ok. But build breaks in the process for some reason.

**Comment by divVerent** [comment] 2022-05-18 21:18
I will try reproducing and fixing this.

BTW the license inclusion can be made optional - it is there to fulfill
obligations regarding inclusion of license texts with redistribution even
for statically linked in Go packages.

However as you seem to use vendoring, you clearly are already aware of all
transitive dependencies and can fulfill this another way.

So I will both fix this and make it skippable.

**Comment by divVerent** [comment] 2022-05-19 11:41
I cannot reproduce the issue - can you give more instructions and full build attempt logs?

I did:

```
$ git clean -xdf
$ gmake BUILDTYPE=release
(succeeded, but warned about a GLAPIENTRY redefinition)
$ ./aaaaxy -dump_embedded_assets=/tmp/foo
(showed an error xmessage - got to fix that as this early exit is intentional)
$ ls -la /tmp/foo/software-licenses
(contains expected data)
```

**Comment by yurivict** [comment] 2022-05-19 15:52
```
===>  Building for aaaaxy-1.2.34
cd /disk-samsung/freebsd-ports/games/aaaaxy/work/github.com/divVerent/aaaaxy@v1.2.34 && /usr/bin/env XDG_DATA_HOME=/disk-samsung/freebsd-ports/games/aaaaxy/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/games/aaaaxy/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/games/aaaaxy/work/.cache  HOME=/disk-samsung/freebsd-ports/games/aaaaxy/work PATH=/disk-samsung/freebsd-ports/games/aaaaxy/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" CGO_ENABLED=1  CGO_CFLAGS="-I/usr/local/include"  CGO_LDFLAGS="-L/usr/local/lib"  GOARM= GOPATH="/disk-samsung/freebsd-ports/distfiles/go/games_aaaaxy"  GOBIN="/disk-samsung/freebsd-ports/games/aaaaxy/work/bin"  GO111MODULE=on  GOFLAGS=-modcacherw  GOSUMDB=sum.golang.org GOPROXY=off AAAAXY_BUILD_USE_VERSION_FILE=true gmake GO_FLAGS="-tags=embed -a -trimpath -v -buildmode=exe -trimpath -ldflags=-s -buildvcs=false -mod=vendor" BUILDTYPE=release
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/games/aaaaxy/work/github.com/divVerent/aaaaxy@v1.2.34'
go generate -tags=embed -a -trimpath -v -buildmode=exe -trimpath -ldflags=-s -buildvcs=false -mod=vendor
generate.go
+ : go
+ export 'GOOS='
+ export 'GOARCH='
+ mkdir -p assets/generated
+ [ x '=' xtrue ]
+ cp assets/_saved/image_load_order.txt assets/_saved/level.cp.json assets/generated/
+ scripts/version.sh semver
NOTE: version imported from .lastreleaseversion file.
NOTE: when building from a git clone, this message should not show up.
generate_embed.go
+ : go
+ export 'GOOS='
+ export 'GOARCH='
+ out=''
+ rm -rf licenses/software-licenses
+ go run github.com/google/go-licenses save github.com/divVerent/aaaaxy --force '--save_path=licenses/software-licenses'
package github.com/google/go-licenses: no Go files in /disk-samsung/freebsd-ports/games/aaaaxy/work/github.com/divVerent/aaaaxy@v1.2.34/vendor/github.com/google/go-licenses
+ true
+ [ -d 'licenses/software-licenses/*/' ]
generate_embed.go:20: running "sh": exit status 1
gmake[1]: *** [Makefile:110: generate] Error 1
gmake[1]: Leaving directory '/disk-samsung/freebsd-ports/games/aaaaxy/work/github.com/divVerent/aaaaxy@v1.2.34'
*** Error code 2
```

**Comment by divVerent** [comment] 2022-05-19 16:57
Thanks, this helps.

So the real issue was that go-licenses didn't work because apparently you didn't include it among the vendorized packages.

This should not be able to happen - I intentionally created this "nonsense" package here:

https://github.com/divVerent/aaaaxy/blob/9289ad63c716d971fb7bcb918fb396fd87bdad50/internal/builddeps/builddeps.go

so that go.mod contains go-licenses and other build time dependencies even if they're only needed on some OSes.

Or has the real problem been the not-respecting of GO_FLAGS which I've fixed by now?

Anyway - I am closing this issue now - seems like the glob pattern is fine, and the real issue was the failure to run go-licenses. Next week I will pack a release tarball with the fixes accumulated so far, including GO_FLAGS and making license inclusion optional (after all, a properly made FreeBSD package can install these files in a better way anyway).

**Closed** 2022-05-19 16:58 UTC
